name: Sync Database to Chatbot

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call PHP Script
        run: curl "https://74fa7e71af33.ngrok-free.app/lgu-2-main/update_chatbot.php"
